#!/usr/bin/env bash
# Phase 10 gate: the story is told with only numbers this repo produced.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib.sh"
cd "$REPO_ROOT"

PY="$(venv_python)"

step "README renders from the template"
[ -f README.template.md ] || fail "README.template.md is missing"
"$PY" scripts/render_readme.py | sed 's/^/    /' || fail "render failed"
ok "every placeholder resolved against data/results"

step "no placeholder sits inside a markdown table"
# prettier aligns table columns against the *placeholder* text, which is far longer than
# the number that replaces it. That produced misaligned tables, `|` padding that broke the
# placeholder pattern outright, and escaped `\*\*` in the published README. Both files are
# in .prettierignore now; this keeps the shape that made them safe to hand-wrap.
if grep -nE '^\|.*\{\{\s*result' README.template.md; then
  fail "move these placeholders out of the table; a formatter will mangle them"
fi
ok "placeholders live in prose and lists only"

step "no number in the README was typed by hand"
# The whole point: a figure with no provenance is a claim about mainnet that nothing can
# reproduce, and the README is where a stale number does most damage and is least noticed.
"$PY" scripts/verify_readme_numbers.py | sed 's/^/    /' \
  || fail "README contains a number that no result file produced"
ok "README.md is current and fully sourced"

step "the rendered README is committed"
# Rendering in CI and forgetting to commit would leave the published README stale while
# every check passes.
git diff --quiet -- README.md \
  || fail "README.md differs from its render; run 'make readme' and commit"
ok "no drift between template and rendered file"

step "graphics are generated, not drawn by hand"
"$PY" scripts/render_graphics.py | sed 's/^/    /' || fail "graphics generation failed"
# dashboard.png is a screen capture of the running app, so it is exempt from the rebuild
# check — it is regenerated by `scripts/demo.sh`, not by the renderer.
git diff --quiet -- docs/assets \
  || fail "docs/assets differs from its render; run 'make readme' and commit"
for asset in banner.svg logo.svg logo-seal.svg logo-wordmark.svg \
             attack.svg mechanism.svg precision.svg census.svg; do
  [ -f "docs/assets/$asset" ] || fail "docs/assets/$asset is missing"
done
# Screen captures are produced by scripts/capture_dashboard.mjs, not the SVG renderer, so
# they are checked for existence only.
for shot in landing.png landing-value.png dashboard-hooks.png dashboard-detection.png; do
  [ -f "docs/assets/$shot" ] || fail "docs/assets/$shot is missing; run node scripts/capture_dashboard.mjs"
done
ok "diagrams and charts rebuild to the committed bytes"

step "every link in the README resolves"
"$PY" - <<'PYEOF' || fail "README has a broken link"
import re, sys
from pathlib import Path

text = Path("README.md").read_text(encoding="utf-8")
missing = []
for target in re.findall(r"\]\(([^)]+)\)", text):
    if target.startswith(("http://", "https://", "mailto:")):
        continue
    path = target.split("#", 1)[0]
    if path and not Path(path).exists():
        missing.append(target)

anchors = {
    re.sub(r"[^a-z0-9 -]", "", h.lower()).strip().replace(" ", "-")
    for h in re.findall(r"^#{1,6}\s+(.*)$", text, re.M)
}
for target in re.findall(r"\]\((#[^)]+)\)", text):
    if target[1:] not in anchors:
        missing.append(f"{target} (no such heading)")

if missing:
    for m in missing:
        print(f"    broken: {m}")
    sys.exit(1)
print("    all relative links and anchors resolve")
PYEOF
ok "nothing points at a file or heading that does not exist"

step "the README points at real contract lines"
# A prize requirement and a maintenance hazard in one: line anchors rot the moment anyone
# edits a contract, and a reviewer following a stale `#L178` lands on whitespace.
"$PY" - <<'PYEOF' || fail "a contract line anchor in the README does not resolve"
import re, sys
from pathlib import Path

text = Path("README.md").read_text(encoding="utf-8")
anchors = re.findall(r"\]\((contracts/[^)#]+)#L(\d+)\)", text)
if not anchors:
    print("    no contract line anchors; reviewers cannot verify the integration")
    sys.exit(1)

bad = []
for path, line in anchors:
    p, n = Path(path), int(line)
    if not p.is_file():
        bad.append(f"{path} does not exist")
        continue
    lines = p.read_text(encoding="utf-8").split("\n")
    if n > len(lines) or not lines[n - 1].strip():
        bad.append(f"{path}#L{n} is past the end of the file or points at a blank line")

for b in bad:
    print(f"    {b}")
if bad:
    sys.exit(1)
print(f"    {len(anchors)} contract line anchors all resolve to real code")
PYEOF
ok "reviewers can verify every claim at the line that makes it"

step "the repository is publishable"
# Checked here because the submission requires a public repo, and the checks that matter
# before flipping that switch are all local.
[ -f LICENSE ] || fail "no LICENSE; the submission requires open-source code"
git ls-files --error-unmatch .env >/dev/null 2>&1 && fail ".env is tracked"
grep -qE "^\.env$" .gitignore || fail ".env is not gitignored"
leaked=$(git rev-list --all | while read -r c; do
  git grep -hoE "alch_[A-Za-z0-9_-]+|https?://[A-Za-z0-9._-]*quiknode\.pro/[A-Za-z0-9]+" "$c" 2>/dev/null
done | sort -u | grep -v "alch_EXAMPLEkeyDoNotUse0000" || true)
[ -z "$leaked" ] || { printf '    %s\n' "$leaked"; fail "a provider credential appears in git history"; }
ok "MIT licensed, .env untracked, no credential anywhere in history"

step "FEEDBACK.md has the four required sections"
for section in \
  "Time to first success" \
  "Friction, in order of cost" \
  "The missing capability" \
  "The one improvement with the greatest impact" ; do
  grep -q "^## $section" FEEDBACK.md || fail "FEEDBACK.md is missing: $section"
done
ok "all four sections present"

step "the README states its limits"
# A README that only lists findings is marketing. This is the section that makes the
# findings usable by someone deciding whether to believe them.
grep -qi "threat model and limits" README.md || fail "README has no limits section"
grep -qi "noise floor\|over-delivered\|false-positive" README.md \
  || fail "README states a divergence headline without its measurement error"
ok "limits and the measurement's own error are published"

step "the headline uses an honest denominator"
"$PY" - <<'PYEOF' || fail "divergence headline has no eligible-hook denominator"
import json, sys
doc = json.load(open("data/results/divergence.json"))
t = doc["totals"]
if "eligible_hooks" not in t:
    print("    totals.eligible_hooks missing: '15 of 1404' and '15 of 25' are different claims")
    sys.exit(1)
nf = doc.get("noise_floor", {})
if "estimated_false_positive_share" not in nf:
    print("    noise_floor.estimated_false_positive_share missing")
    sys.exit(1)
print(
    f"    {t['divergent_hooks']} divergent of {t['eligible_hooks']} eligible; "
    f"~{nf['estimated_false_positive_share']:.0%} of charged fills are error"
)
PYEOF
ok "denominator and error published next to the number"
