#!/usr/bin/env bash
# Phase 10 gate: the story is told with only numbers this repo produced.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib.sh"
cd "$REPO_ROOT"

PY="$(venv_python)"

step "README renders from the template"
[ -f README.template.md ] || fail "README.template.md is missing"
"$PY" scripts/render_readme.py | sed 's/^/    /' || fail "render failed"
# The rendered file is then formatted, exactly as `make readme` does it, so that the drift
# check below compares like with like rather than flagging prettier's own output.
npx --yes prettier --write README.md README.template.md >/dev/null 2>&1 \
  || fail "prettier failed on the rendered README"
ok "every placeholder resolved against data/results"

step "no number in the README was typed by hand"
# The whole point: a figure with no provenance is a claim about mainnet that nothing can
# reproduce, and the README is where a stale number does most damage and is least noticed.
"$PY" scripts/verify_readme_numbers.py | sed 's/^/    /' \
  || fail "README contains a number that no result file produced"
ok "README.md is current and fully sourced"

step "the rendered README is committed"
# Rendering in CI and forgetting to commit would leave the published README stale while
# every check passes.
git diff --quiet -- README.md \
  || fail "README.md differs from its render; run 'make readme' and commit"
ok "no drift between template and rendered file"

step "graphics are generated, not drawn by hand"
"$PY" scripts/render_graphics.py | sed 's/^/    /' || fail "graphics generation failed"
# dashboard.png is a screen capture of the running app, so it is exempt from the rebuild
# check — it is regenerated by `scripts/demo.sh`, not by the renderer.
git diff --quiet -- docs/assets \
  || fail "docs/assets differs from its render; run 'make readme' and commit"
for asset in attack.svg mechanism.svg precision.svg census.svg dashboard.png; do
  [ -f "docs/assets/$asset" ] || fail "docs/assets/$asset is missing"
done
ok "diagrams and charts rebuild to the committed bytes"

step "every link in the README resolves"
"$PY" - <<'PYEOF' || fail "README has a broken link"
import re, sys
from pathlib import Path

text = Path("README.md").read_text(encoding="utf-8")
missing = []
for target in re.findall(r"\]\(([^)]+)\)", text):
    if target.startswith(("http://", "https://", "mailto:")):
        continue
    path = target.split("#", 1)[0]
    if path and not Path(path).exists():
        missing.append(target)

anchors = {
    re.sub(r"[^a-z0-9 -]", "", h.lower()).strip().replace(" ", "-")
    for h in re.findall(r"^#{1,6}\s+(.*)$", text, re.M)
}
for target in re.findall(r"\]\((#[^)]+)\)", text):
    if target[1:] not in anchors:
        missing.append(f"{target} (no such heading)")

if missing:
    for m in missing:
        print(f"    broken: {m}")
    sys.exit(1)
print("    all relative links and anchors resolve")
PYEOF
ok "nothing points at a file or heading that does not exist"

step "FEEDBACK.md has the four required sections"
for section in \
  "Time to first success" \
  "Friction, in order of cost" \
  "The missing capability" \
  "The one improvement with the greatest impact" ; do
  grep -q "^## $section" FEEDBACK.md || fail "FEEDBACK.md is missing: $section"
done
ok "all four sections present"

step "the README states its limits"
# A README that only lists findings is marketing. This is the section that makes the
# findings usable by someone deciding whether to believe them.
grep -qi "threat model and limits" README.md || fail "README has no limits section"
grep -qi "noise floor\|over-delivered\|false-positive" README.md \
  || fail "README states a divergence headline without its measurement error"
ok "limits and the measurement's own error are published"

step "the headline uses an honest denominator"
"$PY" - <<'PYEOF' || fail "divergence headline has no eligible-hook denominator"
import json, sys
doc = json.load(open("data/results/divergence.json"))
t = doc["totals"]
if "eligible_hooks" not in t:
    print("    totals.eligible_hooks missing: '15 of 1404' and '15 of 25' are different claims")
    sys.exit(1)
nf = doc.get("noise_floor", {})
if "estimated_false_positive_share" not in nf:
    print("    noise_floor.estimated_false_positive_share missing")
    sys.exit(1)
print(
    f"    {t['divergent_hooks']} divergent of {t['eligible_hooks']} eligible; "
    f"~{nf['estimated_false_positive_share']:.0%} of charged fills are error"
)
PYEOF
ok "denominator and error published next to the number"
